import { Dimensions, Platform, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

export const getTheme = (isDarkMode: boolean) => ({
  bg: isDarkMode ? "#0f172a" : "#f1f5f9",
  card: isDarkMode ? "#1e293b" : "#ffffff",
  text: isDarkMode ? "#f8fafc" : "#0f172a",
  muted: isDarkMode ? "#94a3b8" : "#64748b",
  border: isDarkMode ? "#334155" : "#e2e8f0",
  primary: "#059669",
  primaryDark: "#064e3b",
  secondary: "#10b981",
  danger: "#ef4444",
  dangerLight: isDarkMode ? "#450a0a" : "#fee2e2",
  info: "#38bdf8",
  infoLight: isDarkMode ? "#0c4a6e" : "#e0f2fe",
  warning: "#f59e0b",
  warningLight: isDarkMode ? "#78350f" : "#fef3c7",
});

export const createStyles = (theme: ReturnType<typeof getTheme>) =>
  StyleSheet.create({
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.bg,
    },

    // LOGIN
    loginContainer: {
      flex: 1,
      justifyContent: "center",
      padding: 25,
      backgroundColor: theme.primary,
    },
    loginBox: {
      padding: 30,
      borderRadius: 24,
      elevation: 15,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 20,
      backgroundColor: theme.card,
    },
    loginTitle: {
      fontSize: 32,
      fontWeight: "900",
      textAlign: "center",
      letterSpacing: -1,
      marginBottom: 5,
      color: theme.primary,
    },
    loginSubtitle: {
      fontSize: 14,
      textAlign: "center",
      marginBottom: 30,
      fontWeight: "600",
      color: theme.muted,
    },
    label: {
      fontSize: 12,
      fontWeight: "800",
      marginBottom: 6,
      marginTop: 10,
      textTransform: "uppercase",
      color: theme.text,
    },
    input: {
      borderWidth: 1,
      padding: 15,
      borderRadius: 12,
      marginBottom: 15,
      fontSize: 16,
      backgroundColor: theme.bg,
      color: theme.text,
      borderColor: theme.border,
    },
    btnPrimary: {
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
      backgroundColor: theme.primary,
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
    },
    btnText: {
      color: "white",
      fontWeight: "900",
      fontSize: 14,
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    btnOutline: {
      padding: 15,
      borderRadius: 12,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
    },
    btnOutlineText: { fontWeight: "800", fontSize: 14, color: theme.text },

    // ESTRUTURA GERAL
    appContainer: { flex: 1, backgroundColor: theme.bg },
    header: {
      padding: 20,
      paddingTop: Platform.OS === "ios" ? 55 : 40,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottomWidth: 1,
      elevation: 5,
      zIndex: 10,
      backgroundColor: theme.primaryDark,
      borderBottomColor: theme.primaryDark,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "900",
      letterSpacing: -0.5,
      color: "white",
    },
    statusDot: { width: 10, height: 10, borderRadius: 5 },
    pingContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: "rgba(0,0,0,0.2)",
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 15,
    },
    contentScroll: { padding: 20, paddingBottom: 130 },
    sectionTitle: {
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 15,
      letterSpacing: -0.5,
      color: theme.text,
    },
    flexHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 15,
    },

    // PESQUISA E FILTROS
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 12,
      paddingHorizontal: 15,
      paddingVertical: 10,
      marginBottom: 15,
    },
    searchInput: { flex: 1, marginLeft: 10, fontSize: 16, color: theme.text },
    filterBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      backgroundColor: theme.card,
      borderColor: theme.border,
      flex: 1,
      justifyContent: "center",
    },

    // SIDEBAR MENU
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      zIndex: 100,
    },
    sidebar: {
      position: "absolute",
      top: 0,
      bottom: 0,
      left: 0,
      width: screenWidth * 0.8,
      zIndex: 101,
      elevation: 20,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 15,
      backgroundColor: theme.card,
    },
    sidebarHeader: {
      padding: 25,
      paddingTop: Platform.OS === "ios" ? 60 : 40,
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      backgroundColor: theme.primaryDark,
    },
    sidebarTitle: { color: "white", fontSize: 24, fontWeight: "900" },
    navItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 20,
      borderLeftWidth: 4,
      borderLeftColor: "transparent",
    },
    navText: { fontSize: 16 },

    // DASHBOARD
    summaryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 20,
    },
    summaryCard: {
      width: "48%",
      padding: 18,
      borderRadius: 16,
      marginBottom: 15,
      borderWidth: 1,
      backgroundColor: theme.card,
      borderColor: theme.border,
      elevation: 2,
    },
    summaryLabel: {
      fontSize: 11,
      fontWeight: "900",
      textTransform: "uppercase",
      marginBottom: 8,
      color: theme.muted,
    },
    summaryValue: { fontSize: 36, fontWeight: "900", color: theme.text },
    alertCard: {
      padding: 18,
      borderRadius: 16,
      borderLeftWidth: 6,
      marginBottom: 15,
      elevation: 1,
    },
    alertTop: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    alertEquip: { fontSize: 18, fontWeight: "900", marginLeft: 10 },
    alertMsg: {
      fontSize: 15,
      marginBottom: 15,
      lineHeight: 22,
      fontWeight: "600",
      color: theme.text,
    },
    emptyState: {
      alignItems: "center",
      padding: 50,
      borderRadius: 16,
      borderWidth: 2,
      borderStyle: "dashed",
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    emptyStateText: {
      fontSize: 20,
      fontWeight: "900",
      marginTop: 15,
      color: theme.text,
    },

    // SENSORES
    motorCard: {
      padding: 18,
      borderRadius: 16,
      marginBottom: 15,
      borderLeftWidth: 6,
      borderWidth: 1,
      backgroundColor: theme.card,
      borderColor: theme.border,
      elevation: 2,
    },
    motorHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 15,
    },
    motorTitle: { fontSize: 18, fontWeight: "900", color: theme.text },
    badgeSetor: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 10,
      fontSize: 10,
      fontWeight: "900",
      alignSelf: "flex-start",
      textTransform: "uppercase",
      marginBottom: 10,
      backgroundColor: theme.bg,
      color: theme.text,
    },
    statusBox: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
    },
    statusInfo: { flex: 1 },
    statusText: {
      color: "white",
      fontWeight: "900",
      fontSize: 15,
      marginTop: 5,
      letterSpacing: 0.5,
    },
    statusLimits: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 11,
      fontWeight: "600",
      marginTop: 4,
    },
    thermalBarBg: {
      width: "90%",
      height: 6,
      backgroundColor: "rgba(0,0,0,0.2)",
      borderRadius: 3,
      marginTop: 12,
      overflow: "hidden",
    },
    thermalBarFill: { height: "100%", borderRadius: 3 },
    tempDisplay: {
      backgroundColor: "rgba(0,0,0,0.2)",
      padding: 12,
      borderRadius: 10,
      alignItems: "center",
      minWidth: 65,
    },
    tempDisplayLabel: {
      color: "rgba(255,255,255,0.8)",
      fontSize: 10,
      textTransform: "uppercase",
      fontWeight: "900",
      marginBottom: 2,
    },
    tempDisplayValue: { color: "white", fontSize: 20, fontWeight: "900" },

    // LISTAGENS & TABELA BRUTA
    listCard: {
      padding: 18,
      borderRadius: 16,
      marginBottom: 12,
      borderWidth: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    listTitle: { fontSize: 18, fontWeight: "900", color: theme.text },
    listSub: {
      fontSize: 13,
      marginTop: 4,
      fontWeight: "600",
      color: theme.muted,
    },
    listActions: { flexDirection: "row", gap: 12 },
    actionBtn: { padding: 10, borderRadius: 10, backgroundColor: theme.bg },

    tableRow: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      paddingVertical: 10,
      alignItems: "center",
    },
    tableCell: { flex: 1, fontSize: 12, color: theme.text },
    tableHeader: {
      fontWeight: "900",
      color: theme.muted,
      textTransform: "uppercase",
    },

    // MODAIS & TOAST
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.65)",
      justifyContent: "center",
      padding: 20,
    },
    modalContent: {
      padding: 25,
      borderRadius: 24,
      borderWidth: 1,
      backgroundColor: theme.card,
      borderColor: theme.border,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 8,
      color: theme.text,
      letterSpacing: -0.5,
    },
    modalSub: {
      fontSize: 15,
      marginBottom: 20,
      color: theme.muted,
      fontWeight: "500",
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 20,
    },
    toast: {
      position: "absolute",
      top: Platform.OS === "ios" ? 60 : 40,
      left: 20,
      right: 20,
      padding: 18,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      elevation: 15,
      zIndex: 9999,
    },
    toastText: {
      color: "white",
      fontWeight: "800",
      marginLeft: 12,
      fontSize: 15,
    },
  });

export default function StylesPlaceholder() {
  return null;
}
